'use client';
import {useEffect,useRef,useState} from 'react';
import topics from '../data/topics';
import {schedule} from '../data/schedule';
import {AppState,DailyEntry,DayProgress,Lang,Theme} from '../types';

const H=3600000;
const initial:AppState={version:4,name:'',hours:7,level:'beginner',goal:'foundation',studyStyle:'balanced',lang:'en',theme:'redgreen',intensity:'normal',jokeFrequency:'normal',briefing:'full',sound:false,notifications:false,daily:{},breakStartedAt:null,breaksUsed:0,streak:0,longestStreak:0,lastCompletedDate:null,coachHistory:[],timer:{running:false,sessionStartedAt:null,accumulatedMs:0,lastSyncedAt:null,date:null}};
const str=(ms:number)=>{const n=Math.max(0,Math.floor(ms/1000));return [Math.floor(n/3600),Math.floor(n%3600/60),n%60].map(x=>String(x).padStart(2,'0')).join(':')};
const words={en:{dashboard:'Dashboard',calendar:'Calendar',settings:'Settings',welcome:'Welcome',hello:'Good morning',mood:'How are you feeling today?',mission:'Today’s mission',target:'Daily target',studied:'Studied',remaining:'Remaining',day:'Day',theory:'Theory',practical:'Practical',videos:'Video searches',resources:'Practical resources',discord:'Review the resources shared in your Discord server',start:'Start study',pause:'Pause',save:'Stop and save',progress:'Progress',name:'Your name',language:'Language',hours:'Daily study hours',mode:'Display mode',level:'Current level',goal:'Main goal',style:'Study style',saveProfile:'Save and enter',edit:'Edit profile',noTime:'The timer stops at your daily target.',satr:'Satr platform · day',intro:'Set up your study plan',next:'Next',back:'Back',export:'Export progress',import:'Import progress',reset:'Reset progress',today:'Today',done:'Completed',upcoming:'Upcoming',review:'Discord resource review',study:'Study',linksNote:'Video links open a topic-specific search. Choose a suitable lesson; individual videos have not been curated.',completed:'Mark complete',open:'Open day',preferences:'Preferences',course:'Focus',beginner:'Beginner',intermediate:'Intermediate',advanced:'Advanced',foundation:'Build fundamentals',practice:'Hands-on practice',competition:'Competition preparation',balanced:'Balanced',visual:'Video first',hands:'Practice first'},ar:{dashboard:'الرئيسية',calendar:'التقويم',settings:'الإعدادات',welcome:'أهلًا',hello:'صباح الخير',mood:'كيف وضعك اليوم؟',mission:'مهمة اليوم',target:'هدف المذاكرة اليومي',studied:'وقت المذاكرة',remaining:'المتبقي',day:'اليوم',theory:'النظري',practical:'العملي',videos:'البحث عن المقاطع',resources:'مصادر التطبيق العملي',discord:'راجع المصادر المنشورة في سيرفر الديسكورد الخاص بك',start:'ابدأ المذاكرة',pause:'إيقاف مؤقت',save:'إيقاف وحفظ',progress:'الإنجاز',name:'اسمك',language:'اللغة',hours:'ساعات المذاكرة اليومية',mode:'وضع العرض',level:'مستواك الحالي',goal:'هدفك الأساسي',style:'أسلوبك المفضل',saveProfile:'احفظ وابدأ',edit:'تعديل الملف',noTime:'يتوقف العداد عند اكتمال هدفك اليومي.',satr:'منصة سطر · اليوم',intro:'جهز خطتك الدراسية',next:'التالي',back:'السابق',export:'تصدير التقدم',import:'استيراد التقدم',reset:'مسح التقدم',today:'اليوم',done:'مكتمل',upcoming:'قادم',review:'مراجعة مصادر الديسكورد',study:'مذاكرة',linksNote:'روابط المقاطع تفتح بحثًا مخصصًا للموضوع؛ اختر الدرس المناسب. لم تُنتقَ مقاطع فردية مسبقًا.',completed:'تحديد مكتمل',open:'افتح اليوم',preferences:'تفضيلاتك',course:'المحور',beginner:'مبتدئ',intermediate:'متوسط',advanced:'متقدم',foundation:'بناء الأساسيات',practice:'تطبيق عملي',competition:'الاستعداد للمسابقة',balanced:'متوازن',visual:'مقاطع أولًا',hands:'تطبيق أولًا'}};
const jokes={ar:['إذا الواي فاي اختفى، لا تتهم الهكر… تأكد أنك دافع الفاتورة أولًا 😭','اليوم بنذاكر لدرجة الـFirewall يقول: خلاص ادخلي ارتاحي 😂','قالوا لي خليك إيجابية، رحت فحصت كل النتائج وطلعت false positive 🤡','إذا شفت كلمة root لا تتحمس، مو معناها صرت مدير الكون 😎','أنا والمذاكرة مثل الـVPN: الاتصال موجود بس السرعة محل نقاش 🫠','سألت الـDNS عن مستقبلي، قال: العنوان غير موجود 😭','المؤقت ما يعض… بس يفضح التسويف بكل أدب ⏱️','الهاكر الحقيقي اليوم هو المنبه اللي اخترق نومك 😴','اللاب يقول جرّب، والكمبيوتر يقول لا تلمسني 😂','أقوى حماية من التسويف: اقفل تبويب المقاطع القطاوة 🐈'],en:['If the Wi-Fi disappears, check the bill before blaming hackers 😭','Study so hard the firewall asks you to take a break 😂','I tried to stay positive and got a false positive 🤡','Seeing root does not make you ruler of the universe 😎','My study focus is like a VPN: connected, but the speed is debatable 🫠','I asked DNS about my future. It said address not found 😭','The timer does not bite, but it politely exposes procrastination ⏱️','Today’s real hacker is the alarm that breached your sleep 😴','The lab says experiment. The laptop says please do not 😂','Best defense against procrastination: close the cat video tab 🐈']};
const practicalLinks=[{title:'Microsoft Learn',url:'https://learn.microsoft.com/en-us/training/'},{title:'Cisco Networking Academy',url:'https://www.netacad.com/'},{title:'TryHackMe',url:'https://tryhackme.com/'},{title:'OverTheWire',url:'https://overthewire.org/wargames/'},{title:'PortSwigger Web Security Academy',url:'https://portswigger.net/web-security'}];
function resources(t:typeof topics[number]){const seen=new Set<string>();return [...t.resources.map(r=>({title:r.title,url:r.url})),...practicalLinks].filter(r=>{if(seen.has(r.url))return false;seen.add(r.url);return true}).slice(0,5)}
function searches(t:typeof topics[number]){return ['introduction','fundamentals','explained','tutorial','hands on lab'].map((part,i)=>({title:`${i+1}. ${t.title} · ${part}`,url:`https://www.youtube.com/results?search_query=${encodeURIComponent(t.title+' cybersecurity '+part)}`}))}
function entryLabel(e:DailyEntry,lang:Lang){if(e.kind==='satr')return lang==='ar'?'منصة سطر':'Satr platform';const t=topics.find(x=>x.id===e.topicId);return t?(lang==='ar'?t.arTitle:t.title):''}
function migrateDaily(data:AppState):Record<string,DayProgress>{
 const migrated:Record<string,DayProgress>={};
 if(data.version>=4){Object.assign(migrated,data.daily)}else{
  Object.entries(data.daily as Record<string,DayProgress>).forEach(([key,value])=>{const match=/^day-(\d+)$/.exec(key);if(match&&Number(match[1])<=50)migrated[`day-${Number(match[1])+3}`]=value});
  for(let i=0;i<50;i++){const legacy=new Date(Date.UTC(2026,8,23+i)).toISOString().slice(0,10);const key=`day-${i+4}`;if(!migrated[key]&&data.daily[legacy])migrated[key]=data.daily[legacy]}
 }

 return migrated;
}
export default function Home(){
 const [state,setState]=useState<AppState>(initial),[loaded,setLoaded]=useState(false),[now,setNow]=useState(Date.now()),[page,setPage]=useState<'dashboard'|'calendar'|'settings'|'day'>('dashboard'),[chosen,setChosen]=useState<DailyEntry|null>(null),[step,setStep]=useState(0),[onboarded,setOnboarded]=useState(false),[mood,setMood]=useState('focused');const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const old=JSON.parse(localStorage.getItem('cyber7h-state')||'null');if(old&&typeof old==='object'&&old.daily){
 const migrated=migrateDaily(old as AppState);
 setOnboarded(Boolean(old.name)&&localStorage.getItem('cyber-coach-onboarded')!=='false');setState({...initial,...old,version:4,name:old.name||'',hours:Math.min(16,Math.max(1,Number(old.hours)||7)),daily:migrated,timer:{...initial.timer,...old.timer,running:false,sessionStartedAt:null,accumulatedMs:(old.timer?.accumulatedMs||0)+(old.timer?.running&&old.timer?.sessionStartedAt?Math.max(0,Math.min(Date.now()-old.timer.sessionStartedAt,(Number(old.hours)||7)*H)):0)}})}}catch{}setLoaded(true)},[]);
 useEffect(()=>{if(loaded){localStorage.setItem('cyber7h-state',JSON.stringify(state));document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==='ar'?'rtl':'ltr'}},[state,loaded]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
 const l=state.lang,T=words[l],index=Math.min(52,Math.max(0,schedule.findIndex(x=>!state.daily[x.date]?.completed)===-1?52:schedule.findIndex(x=>!state.daily[x.date]?.completed))),todayEntry=schedule[index],entry=chosen||todayEntry,topic=topics.find(t=>t.id===entry.topicId)||{...topics[0],title:'Satr platform',arTitle:'منصة سطر',why:'Study the Satr platform track at your own pace.',arWhy:'تابع مسار منصة سطر بالوتيرة التي تناسبك.',theory:[],practical:[],resources:[]},todayProgress=state.daily[todayEntry.date]||{studyMs:0,theory:[],practical:[]};
 const same=state.timer.date===todayEntry.date||(!state.timer.date&&Object.keys(state.daily).length===0),base=same?state.timer.accumulatedMs:0,elapsed=state.timer.running&&same&&state.timer.sessionStartedAt?Math.max(0,now-state.timer.sessionStartedAt):0,spent=Math.min(state.hours*H,Math.max(todayProgress.studyMs,base+elapsed)),remaining=Math.max(0,state.hours*H-spent),pct=Math.round(100*spent/(state.hours*H));
 const save=(patch:Partial<AppState>)=>setState(s=>({...s,...patch}));
 useEffect(()=>{if(!loaded)return;if(state.timer.running&&remaining===0){setState(s=>{if(!s.timer.running)return s;const old=s.daily[todayEntry.date]||{studyMs:0,theory:[],practical:[]};return {...s,daily:{...s.daily,[todayEntry.date]:{...old,studyMs:s.hours*H,completed:true}},timer:{running:false,sessionStartedAt:null,accumulatedMs:s.hours*H,lastSyncedAt:Date.now(),date:todayEntry.date}}})}},[remaining,loaded,state.timer.running,todayEntry.date]);
 const pause=()=>setState(s=>({...s,timer:{...s.timer,running:false,sessionStartedAt:null,accumulatedMs:spent,lastSyncedAt:Date.now(),date:todayEntry.date},daily:{...s.daily,[todayEntry.date]:{...(s.daily[todayEntry.date]||{studyMs:0,theory:[],practical:[]}),studyMs:spent,completed:spent>=s.hours*H}}}));
 const start=()=>{if(remaining<=0)return;setState(s=>({...s,timer:{running:true,sessionStartedAt:Date.now(),accumulatedMs:spent,lastSyncedAt:Date.now(),date:todayEntry.date}}))};
 const toggle=(kind:'theory'|'practical',id:string)=>setState(s=>{const p=s.daily[entry.date]||{studyMs:0,theory:[],practical:[]};return {...s,daily:{...s.daily,[entry.date]:{...p,[kind]:p[kind].includes(id)?p[kind].filter(x=>x!==id):[...p[kind],id]}}}});
 const check=state.daily[entry.date]||{studyMs:0,theory:[],practical:[]};
 const exportData=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='cyber-coach-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)};
 const importData=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;f.text().then(raw=>{try{const x=JSON.parse(raw);if(!x||typeof x.daily!=='object'||!x.timer||typeof x.name!=='string')throw Error();setState({...initial,...x,version:4,daily:migrateDaily(x as AppState),timer:{...initial.timer,...x.timer,running:false,sessionStartedAt:null}})}catch{alert(l==='ar'?'ملف التقدم غير صالح':'Invalid progress file')}});e.target.value=''};
 const jokeFor=(dayIndex:number)=>jokes[l][(Math.max(0,dayIndex)+Math.floor(Math.max(0,dayIndex)/10))%jokes[l].length];
 const dailyJoke=jokeFor(index);
 const nav=(['dashboard','calendar','settings'] as const);
 if(!loaded)return <main className="main">Loading…</main>;
 const select=(d:DailyEntry)=>{setChosen(d);setPage('day');window.scrollTo(0,0)};
 return <div className={`app theme-${state.theme} ${l==='ar'?'rtl':''}`}><div className="shell"><aside className="sidebar"><div className="brand-mark"><span>53</span><div><b>CYBERSECURITY</b><small>STUDY COACH</small></div></div><nav className="nav">{nav.map((n,i)=><button key={n} className={page===n?'active':''} onClick={()=>{setChosen(null);setPage(n)}}><span className="nav-icon">{['⌂','▦','⚙'][i]}</span>{T[n]}</button>)}</nav><div className="side-mission"><strong>{Math.min(53,Math.max(1,index+1))}/53</strong><span>{T.progress}</span></div></aside><main className="main"><header className="topbar"><div><div className="breadcrumb">CYBERSECURITY · 53 DAYS</div><div className="date-line">{l==='ar'?'ابدأ في الوقت الذي تختاره':'Start on your own schedule'}</div></div><button className="lang-switch" onClick={()=>save({lang:l==='ar'?'en':'ar'})}>{l==='ar'?'English':'العربية'}</button></header>
 {!onboarded?<div className="onboarding-backdrop"><section className="panel setup" role="dialog" aria-modal="true" aria-labelledby="onboarding-title"><div className="eyebrow">{step===0?T.welcome:`${step}/3 · ${T.intro}`}</div><h1 id="onboarding-title">{step===0?(l==='ar'?'أهلًا! 👋':'Welcome! 👋'):step===1?T.name:step===2?T.language:T.hours}</h1>{step===0?<><p>{l==='ar'?'جهازك ما يحتاج تحديث… يحتاجك تبدأ قبل ما يصير المؤقت أثرًا تاريخيًا 😂':'Your computer does not need an update. It needs you to start before the timer becomes a historical artifact 😂'}</p><h2>{l==='ar'?'يلا نكمل؟':'Ready to continue?'}</h2></>:step===1?<label className="setup-field">{T.name}<input autoFocus value={state.name} onChange={e=>{localStorage.setItem('cyber-coach-onboarded','false');save({name:e.target.value})}} placeholder={l==='ar'?'اكتب اسمك':'Enter your name'}/></label>:step===2?<label className="setup-field">{T.language}<select value={l} onChange={e=>save({lang:e.target.value as Lang})}><option value="en">English</option><option value="ar">العربية</option></select></label>:<label className="setup-field">{T.hours}<input type="number" min="1" max="16" value={state.hours} onChange={e=>save({hours:Math.min(16,Math.max(1,Number(e.target.value)||1))})}/></label>}<div className="data-actions">{step>0&&<button className="btn" onClick={()=>setStep(step-1)}>{T.back}</button>}<button className="btn primary" onClick={()=>{if(step===1&&!state.name.trim())return;if(step<3)setStep(step+1);else {save({name:state.name.trim()});localStorage.setItem('cyber-coach-onboarded','true');setOnboarded(true)}}}>{step===0?(l==='ar'?'يلا نكمل':'Let’s go'):step===3?T.saveProfile:T.next}</button></div></section></div>:<>
 {page==='dashboard'&&<><section className="hero"><div className="eyebrow">{T.hello} · {T.welcome} {state.name}</div><h1>{T.mission}</h1><p>{T.day} {index+1} / 53 · {entryLabel(todayEntry,l)} {todayEntry.topicDay===2?`· ${T.review}`:''}</p><div className="mood">{T.mood} {['focused','tired','energized'].map((m,i)=><button key={m} className={mood===m?'active':''} onClick={()=>setMood(m)}>{l==='ar'?['مركز','متعب','متحمس'][i]:['Focused','Tired','Energized'][i]}</button>)}</div></section><section className="panel joke-card"><div className="eyebrow">{l==='ar'?'ذبة اليوم · ابتسامة مجانية':'DAILY JOKE · FREE SMILE'}</div><h2>{dailyJoke}</h2><small>{T.day} {index+1} / 53</small></section><section className="stat-grid"><div className="metric-card"><span>{T.target}</span><strong>{state.hours}h</strong></div><div className="metric-card"><span>{T.studied}</span><strong>{str(spent)}</strong></div><div className="metric-card"><span>{T.remaining}</span><strong>{str(remaining)}</strong></div><div className="metric-card"><span>{T.progress}</span><strong>{schedule.filter(x=>state.daily[x.date]?.completed).length}/53</strong></div></section><section className="panel timer-card"><div className="eyebrow">{T.remaining}</div><div className="timer">{str(remaining)}</div><div className="progress large"><i style={{width:`${pct}%`}}/></div><p>{T.noTime}</p><div className="timer-actions">{state.timer.running?<button className="btn primary big" onClick={pause}>{T.pause}</button>:<button className="btn primary big" disabled={!remaining} onClick={start}>{T.start}</button>}<button className="btn big" onClick={pause}>{T.save}</button></div></section><section className="panel"><div className="panel-heading"><h2>{entryLabel(todayEntry,l)}</h2><button className="btn" onClick={()=>select(todayEntry)}>{T.open} →</button></div><p>{l==='ar'?topic.arWhy:topic.why}</p>{todayEntry.kind==='satr'&&<p className="satr-note"><a href="https://satr.codes/" target="_blank" rel="noopener noreferrer">satr.codes ↗</a></p>}{todayEntry.topicDay===2&&<p className="satr-note">{T.discord}</p>}</section></>}
 {page==='calendar'&&<><section className="hero"><div className="eyebrow">{l==='ar'?'ابدأ في الوقت الذي تختاره':'START WHENEVER YOU WANT'}</div><h1>{T.calendar} · 53</h1><p>{l==='ar'?'كل الأيام مفتوحة: ٣ أيام مستقلة لمنصة سطر، ثم ٢٥ موضوعًا، يومان لكل موضوع. ابدأ وقت ما يناسبك.':'All days are open: 3 separate Satr days, then 25 topics with two days each. Start whenever you want.'}</p></section><div className="calendar-grid">{schedule.map((d,i)=>{const p=state.daily[d.date],status=p?.completed?'done':i===index?'today':'upcoming';return <button key={d.date} className={`calendar-day ${status}`} onClick={()=>select(d)}><div className="calendar-top"><b>{i+1}</b><span>{T[status]}</span></div><strong>{entryLabel(d,l)}</strong>{d.kind==='topic'&&<small>{T.day} {d.topicDay}/2</small>}{d.kind==='satr'&&<em>{T.satr} {i+1}/3</em>}{d.topicDay===2&&<em>{T.review}</em>}</button>})}</div></>}
 {page==='day'&&<><button className="btn" onClick={()=>setPage('calendar')}>← {T.calendar}</button><section className="hero"><div className="eyebrow">{T.day} {schedule.indexOf(entry)+1}/53</div><h1>{entryLabel(entry,l)}</h1><p>{l==='ar'?topic.arWhy:topic.why}</p>{entry.topicDay===2&&<p className="satr-note">{T.discord}</p>}</section><section className="panel joke-card"><div className="eyebrow">{l==='ar'?'ذبة اليوم':'DAILY JOKE'}</div><h2>{jokeFor(schedule.indexOf(entry))}</h2></section><section className="stat-grid"><div className="metric-card"><span>{T.target}</span><strong>{state.hours}h</strong></div><div className="metric-card"><span>{T.studied}</span><strong>{str(entry.date===todayEntry.date?spent:check.studyMs)}</strong></div></section>{entry.kind==='satr'?<section className="panel"><h2>{l==='ar'?'رابط منصة سطر':'Satr platform link'}</h2><a className="resource-link" href="https://satr.codes/" target="_blank" rel="noopener noreferrer">satr.codes ↗</a></section>:<><div className="detail-grid"><section className="panel"><h2>{T.theory}</h2>{topic.theory.map(x=><label className="check" key={x.id}><input type="checkbox" checked={check.theory.includes(x.id)} onChange={()=>toggle('theory',x.id)}/><span>{l==='ar'?x.ar:x.en}</span></label>)}</section><section className="panel"><h2>{T.practical}</h2>{topic.practical.map(x=><label className="check" key={x.id}><input type="checkbox" checked={check.practical.includes(x.id)} onChange={()=>toggle('practical',x.id)}/><span>{l==='ar'?x.ar:x.en}</span></label>)}</section></div><div className="detail-grid"><section className="panel"><h2>{T.videos} · 5</h2><p className="muted">{T.linksNote}</p>{searches(topic).map(x=><a className="resource-link" href={x.url} target="_blank" rel="noopener noreferrer" key={x.url}>{x.title} ↗</a>)}</section><section className="panel"><h2>{T.resources} · 5</h2>{resources(topic).map(x=><a className="resource-link" href={x.url} target="_blank" rel="noopener noreferrer" key={x.url}>{x.title} ↗</a>)}</section></div></>}<button className="btn primary" onClick={()=>setState(s=>({...s,daily:{...s.daily,[entry.date]:{...check,studyMs:entry.date===todayEntry.date?spent:check.studyMs,completed:!check.completed}},timer:entry.date===todayEntry.date&&!check.completed?{...s.timer,running:false,sessionStartedAt:null,accumulatedMs:spent}:s.timer}))}>{check.completed?'✓ '+T.done:T.completed}</button></>}
 {page==='settings'&&<><section className="hero"><h1>{T.settings}</h1><p>{T.preferences}</p></section><section className="panel settings-card"><h2>{T.edit}</h2><div className="settings-fields"><label>{T.name}<input value={state.name} onChange={e=>save({name:e.target.value})}/></label><label>{T.hours}<input type="number" min="1" max="16" value={state.hours} onChange={e=>save({hours:Math.min(16,Math.max(1,Number(e.target.value)||1))})}/></label><label>{T.language}<select value={l} onChange={e=>save({lang:e.target.value as Lang})}><option value="en">English</option><option value="ar">العربية</option></select></label><label>{T.style}<select value={state.studyStyle} onChange={e=>save({studyStyle:e.target.value})}>{(['balanced','visual','hands'] as const).map(x=><option key={x} value={x}>{T[x]}</option>)}</select></label></div></section><section className="panel"><h2>{T.mode}</h2><div className="setting-options">{(['redgreen','terminal','futuristic','clean','light'] as Theme[]).map(x=><button className={`choice ${state.theme===x?'active':''}`} key={x} onClick={()=>save({theme:x})}>{x==='redgreen'?(l==='ar'?'أحمر وأسود':'Red & black'):x.toUpperCase()}</button>)}</div></section><section className="panel"><div className="data-actions"><button className="btn" onClick={exportData}>{T.export}</button><button className="btn" onClick={()=>file.current?.click()}>{T.import}</button><input ref={file} type="file" accept="application/json" hidden onChange={importData}/><button className="btn danger" onClick={()=>{if(confirm(l==='ar'?'تأكيد مسح كل التقدم؟':'Erase all progress?')){setState(initial);localStorage.setItem('cyber-coach-onboarded','false');setOnboarded(false);setStep(0)}}}>{T.reset}</button></div></section></>}
 </>}
 </main></div>{state.name&&<nav className="mobile-nav">{nav.map((n,i)=><button key={n} className={page===n?'active':''} onClick={()=>{setChosen(null);setPage(n)}}><span>{['⌂','▦','⚙'][i]}</span>{T[n]}</button>)}</nav>}</div>
}
